### ISSUE TITLE
about train 

### ISSUE THREAD

**Issue by zhunnan** [kxhit/SG_PR#10]
how to generate text file(like 00.txt) of train?

**Comment by kxhit** [comment]
We randomly sample the positive pairs (e.g. <3m) and negative pairs (e.g. >20m) by a ratio (e.g. 1:100) for training. And for evaluation, we remove the easy positive pairs (e.g. <3m & timestamps < 30s). You can refer to the [old version code](gen_sem_kitti_graph_pairs.py)  or [this repo](https://github.com/lilin-hitcrt/SSC/blob/main/script/gen_pairs.py).
Note that the ratio really matters when compared with other methods (Fig.6 in [IROS'21 paper](https://arxiv.org/pdf/2107.00382.pdf)). Please keep all methods compared strictly on the same data distribution.
