### ISSUE TITLE
about the classification part

### ISSUE THREAD

**Issue by lxh990620** [kxhit/SG_PR#11]
Thanks for the great contribution of this research.
 About the visualization part for the dir(data_process),Could you please tell me how could i visualize the .json format 3d data?
by the way,the processed data was classfied into 10 classes for RANGENET++,I would like to know the standard of the classification.
 Thanks a lot.

**Comment by lxh990620** [comment]
I would like to know the algorism of genrating the semantic graph.
Could i consider the .json format data as the semantic graph?
According to Raw input>semantic segmentation>instance segmentation>semantic graph.

Thanks a lot.

**Comment by kxhit** [comment]
Hi! Thanks for your interest in our work!
1. For visualizing the 3D semantic graph, you can simply draw the nodes with colour according to their semantic labels and 3D positions, which are stored in the .json files. We created the visualization with ROS Rviz.
2. For the classification details, you can find [here](https://github.com/kxhit/SG_PR/blob/c7fd67fbe319926f27e82ea1183e10d0d2dffa35/data_process/gen_label_graph.py#L63) that we map the original semantic KITTI labels to ours.
3. Yeah, you can consider .json files as semantic graphs. Each .json represents a semantic graph for the scene and the index is the file name. 

Hope it helps you. Please let me know if anything unclear. Thank you!
