### ISSUE TITLE
How to visualize the Fig.7

### ISSUE THREAD

**Issue by qp-li** [kxhit/SG_PR#12]
Congratulations, author, great work. I really want to know how to visualize Fig. 7 in this paper? Do you have sample code?

**Comment by kxhit** [comment]
Hi - Thanks for your interest.

We didn't provide the visualization code for Fig.7 but it is easy to implement. We randomly pick one query scene and calculate the similarities between it with all the other scenes in this sequence. Then, we color the similarities with some colormap like Jet colormap or any colormap you want.

Please let me know if there is still confusion.
