### ISSUE TITLE
pair_list issue

### ISSUE THREAD

**Issue by crepuscularlight** [kxhit/SG_PR#15]
Hello, this work is quite amazing and most of the documentation is very clear. But I am a little confused about how to generate the pair_list in the train folder in the preprocessed data you have provided.

**Comment by kxhit** [comment]
Hi, thanks for your interest.
I suppose you can refer "data_process" folder and this issue #4 to generate the pair_list from scratch. The basic procedure is as follows. 

1. Firstly convert semantic point clouds to clusters and get one graph (with nodes) for each scene. 
2. And then get positive/negative pairs according to the ground truth distance between the two scenes. You can also change the distance threshold and positive/negative ratio to get different lists. [Here](https://github.com/lilin-hitcrt/SSC/issues/1#issuecomment-875346890) are some other insights into the different ratios and lists that will affect the final results.

Hope it helps.
