### ISSUE TITLE
Ask questions about data usage

### ISSUE THREAD

**Issue by g641** [kxhit/SG_PR#16]
Hello，I have benefited a lot from reading your code. How to use the data in rawdata, such as 00_M2DP_db.npy and 00_gt_db.npy in the M2DP00 folder

**Comment by kxhit** [comment]
Hi, you can check this [code](https://github.com/kxhit/SG_PR/blob/ec94d961573c80234d2a2d13bf730d59dbd723b6/eval_batch.py#L48) to draw the PR curve by using the .npy results. Each corresponding db.npy should have the same size and binary value. 0 indicates the evaluated pair is a negative sample and 1 indicates a positive.

**Comment by g641** [comment]
您好，可以加一下微信交流吗？我是哈工大校友，目前读研二



发自我的iPhone


------------------ Original ------------------
From: Xin Kong ***@***.***&gt;
Date: Fri,Apr 22,2022 5:11 PM
To: kxhit/SG_PR ***@***.***&gt;
Cc: g641 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [kxhit/SG_PR] Ask questions about data usage (Issue #16)





 
Hi, you can check this code to draw the PR curve by using the .npy results. Each corresponding db.npy should have the same size and binary value. 0 indicates the evaluated pair is a negative sample and 1 indicates a positive.

**Comment by g641** [comment]
Hello, can you add WeChat to communicate? I am an alumnus of Harbin Institute of Technology, currently a graduate student, my WeChat is 19819660620
