### ISSUE TITLE
about how to get pre-processing data format

### ISSUE THREAD

**Issue by cama36** [kxhit/SG_PR#17]
Hello, I'd like to ask how i can get the JSON file format you published in advance. For example, there is pose data in the JSON data you published in advance. You did use pose  later, but the data preprocessing code does not involve how to calculate  pose ? Can you help me answer my question.Thank you.

**Comment by kxhit** [comment]
Hi, for the pose info in JSON file is directly obtained from KITTI dataset ground truth data.
