### ISSUE TITLE
How can I use multiple GPUs for training

### ISSUE THREAD

**Issue by Clouds1997** [kxhit/SG_PR#18]
Thank you very much for your open source work，but I do know how to use multiple to train this net，Orz，Please help me T_T

**Comment by kxhit** [comment]
Hi, sorry for the late reply. We didn't implement the multi-GPU version training script as the dataset scale is pretty small and graph representation is quite lightweight.
If you do want to use multi-GPU, I think the standard distributed GPU training tutorial of PyTorch will help you figure it out.

**Comment by Clouds1997** [comment]
thx,bro！
