### ISSUE TITLE
About Comparative Experiment

### ISSUE THREAD

**Issue by Clouds1997** [kxhit/SG_PR#19]
Hello, I would like to ask if the data set of the comparative experiment (such as pointnetvlad) in the paper is also divided according to your script？The pair_list I generated according to this script and I got f1_ score seems that the lowest score is about 0.65， It should not be lower than 0.129 in your paper.

**Comment by kxhit** [comment]
@Clouds1997 Hi, sorry for the late reply. Yes, the comparative experiments are conducted on the same data splits. I rerun all the open-sourced methods on the same data distribution.

For 0.129 I assume you referred to the result of PV-KITTI on sequence 08. Do you train it from scratch on all the other sequences and then evaluate it on sequence 08? I found PointNetVLAD cannot handle reverse loop closure and thus performs very badly on sequence 08. 

Please let me know if anything is still unclear. Thanks!
