### ISSUE TITLE
Time for training 

### ISSUE THREAD

**Issue by chn52979** [kxhit/SG_PR#3]
Hi！I want to know the time required for the network training, and is epochs 500?

**Comment by kxhit** [comment]
Hi! Thanks for your interest in our work!
Firstly, the training sample numbers of different sequences are different. For sequence 08, with batch 128 on a TITAN XP GPU, it costs me around 30 min for one epoch training. In our training script, we will save the best model and usually dozens of epochs should be enough to get a satisfying result.
Hope it helps.
