### ISSUE TITLE
Dalao, how to get graphs_rn and graphs_sk with rangenet++ and Kitti dataset ?

### ISSUE THREAD

**Issue by wenbeier** [kxhit/SG_PR#4]

**Comment by kxhit** [comment]
Hi thanks for your interests!

As mentioned in our paper, we do Euclidean clustering within each semantic categories on semantic point clouds to get instances. For a quick overview, you can refer the implementation below which is quite simple. As the preprocessing code only needs to run once for one dataset, we did not optimize it. It runs quite slow and you can downsample the points to accelerate the euclidean clustering upon your own situation. 

Hope it helps. Let me know if you have further questions. Thanks!

```ruby
def gen_graphs(scan_name, scan, graph_output_dir):
      inst = scan[:, -1] # get instance label
      inst_label_set = list(set(inst))  # get nums of inst
      inst_label_set.sort()
      # print("inst set: ", inst_label_set)
      nodes = []  # graph node
      cluster = []  # cluster -> node
      centers = []
      for id_i in range(len(inst_label_set)):
          index = np.argwhere(inst_label_set[id_i] == inst) # query cluster by instance label
          index = index.reshape(index.shape[0])
          inst_cluster = scan[index, :]
          sem_label = list(set(inst_cluster[:, -2])) # get semantic label
          assert len(sem_label) == 1 # one instance cluster should have only one semantic label
          if int(sem_label[0]) in node_map.keys():
              cluster.append(inst_cluster[:, :3])
              node_label = node_map[int(sem_label[0])]  # add node
              nodes.append(int(node_label))
              cluster_center = np.mean(inst_cluster[:, :3], axis=0)
              centers.append((cluster_center.tolist()))
          elif int(sem_label[0]) == 9 or int(sem_label[0]) == 10: # ignore "road" and "parking"
              continue
          else:
              print("wrong semantic label: ", sem_label[0])
              exit(-1)
```

**Comment by wenbeier** [comment]
Thanks! 
I find in the fuction, the paras 'scan_name' and 'graph_output_dir' are not used, the dict node_map is lose. The core problem is that how convert 'xxx.label'(from rangenet++) with 'pose.txt' to 'xxx.json' files.

**Comment by kxhit** [comment]
Hi~ We just released the preprocessing code for generating graphs. There is some redundant code but I suppose you can find and reorganize them for your own use. Thanks!
