### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Hiram9270** [kxhit/SG_PR#5]
Hello, I want to know how to run your code on the kitti dataset (referring to SG_PR). I hope to give more detailed steps in the readme document. I look forward to your answer, thank you.

**Comment by kxhit** [comment]
Thanks for your interests for our work! Could you describe your problem in more detail? Have you tried to follow up the readme and what's the exact confusion for you? I'd be glad to help you figure it out.

**Comment by Hiram9270** [comment]
This is the case. In your readme document, I have successfully run the test code, which means that I have obtained the maximum score of the F1 and PR curve, and successfully obtained the training data. But in your paper it is stated that you have conducted experiments on the kitti dataset. The first question: I also want to run your code on the kitti data set now. I hope you can give the best address for running on the kitti data set. I am a novice and I was looking for a data set suitable for your code. It took a long time, and then I specifically introduced how to operate it. The readme file is rather vague, so I don't know how to operate. Second question: In the data-process file, I obtained the semantic tags and instance tags by running the code you gave (these are also given in the preprocessed data), but the subsequent output is in the folder and in the The posting on the ros theme makes me wonder, is it to save the semantically segmented pictures in a folder? And how to publish it on the ros theme? I really hope to give more detailed steps. I think the above questions are not difficult for experienced people, but they are really difficult to understand for novices like me. I sincerely hope that the author can give me advice. I have read the papers you wrote. Your research direction is very novel and has a wide range of application scenarios. Finally, if the author can reply to me,This is the case. In your readme document, I have successfully run the test code, which means that I have obtained the maximum score of the PR curve and F1, and successfully obtained the training data. But in your paper it is stated that you have conducted experiments on the kitti dataset. The first question: I also want to run your code on the kitti data set now. I hope you can give the best address for running on the kitti data set. I am a novice and I was looking for a data set suitable for your code. It took a long time, and then I specifically introduced how to operate it. The readme file is rather vague, so I don't know how to operate. Second question: In the data-process file, I obtained the semantic tags and instance tags by running the code you gave (these are also given in the preprocessed data), but the subsequent output is in the folder and in the The posting on the ros theme makes me wonder, is it to save the semantically segmented pictures in a folder? And how to publish it on the ros theme? I really hope to give more detailed steps. I think the above questions are not difficult for experienced people, but they are really difficult to understand for novices like me. I sincerely hope that the author can give me advice. I have read the papers you wrote. Your research direction is very novel and has a wide range of application scenarios. Finally, if the author can reply to me,

**Comment by kxhit** [comment]
Good to know you have successfully run the test code! For generating semantic graphs from scratch, you can refer to this [readme](https://github.com/kxhit/SG_PR/blob/master/data_process/Readme.md#data-preparation). Let me know if you have any troubles.

**Comment by kxhit** [comment]
Please reopen this issue if any problem occurs.
