### ISSUE TITLE
2 bugs about gpu_id

### ISSUE THREAD

**Issue by ssmem** [kxhit/SG_PR#6]
sg_net.py using "cuda:0"
dgcnn.py using "cuda"
your could exchange it with "cuda:"+str(args.gpu_id)

**Comment by kxhit** [comment]
Thanks for your contribution! Please check the new [commit](https://github.com/kxhit/SG_PR/commit/47e995ea76c2229f8ba62b1fb33b9aeb13503eeb) and let me know if everything goes well. You are welcomed to pull requests and contribute to this repo. Thanks!
